# EG-Overlay
# Copyright (c) 2025 Taylor Talkington
# SPDX-License-Identifier: MIT
name: Build EG-Overlay Release Binaries

on:
  push:
    branches:
      - main
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSVC Dev Env
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
            arch: x64
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
      - name: Install Meson
        run: |
            pip install meson
      - name: Build Release
        run: |
          .\scripts\build-release.ps1
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: EG-Overlay
            path: 'release/EG-Overlay/*'
